"use client";

import { useEffect, useState } from "react";

type Investigador = { nombre: string; descripcion?: string; contacto?: string; publicaciones?: string; emerito?: boolean };

const investigadores: Investigador[] = [
  { nombre: "Marina Adamini", descripcion: "Marina Adamini es Licenciada en Sociología y Doctora en Ciencias Sociales por la Universidad Nacional de La Plata, especializada en Sociología del Trabajo. Sus temas de investigación giran en torno a la precarización laboral juvenil y sus implicancias en las identidades sociales. Indaga cómo afectan las transformaciones del mundo del trabajo a la formación identitaria de los jóvenes como trabajadores, y que estrategias individuales y colectivas despliegan frente al avance de la precarización laboral. Actualmente se encuentra investigando las condiciones laborales y formativas de jóvenes trabajadores de la industria informática.\nEs Investigadora Independiente CONICET y Profesora Adjunta en la Universidad Nacional del Centro de la Provincia de Buenos Aires.", contacto: "mailto:marina.adamini@gmail.com", publicaciones: "https://www.conicet.gov.ar/new_scp/detalle.php?keywords=&id=30547&datos_academicos=yes" },
  { nombre: "Lucas Bilbao", descripcion: "Lucas Bilbao es Doctor en Historia por la Universidad Nacional del Centro de la Provincia de Buenos Aires. Sus investigaciones se centran el estudio del catolicismo, el clero y la Iglesia en los siglos XIX y XX. También ha desarrollado trabajos sobre el Vicariato Castrense y las relaciones entre la Iglesia y las FF. AA. durante la segunda mitad del siglo XX, con énfasis en las décadas de 1960 y 1970. Actualmente investiga el desarrollo, despliegue y agencias de las congregaciones religiosas masculinas y femeninas en la provincia de Buenos Aires, entre las últimas décadas del siglo XIX y las primeras del XX.", contacto: "mailto:bilbaolucas@gmail.com", publicaciones: "https://datosdeinvestigacion.conicet.gov.ar/authorDatos/41842" },
  { nombre: "Gisela Coronado Schwindt", descripcion: "Gisela Coronado Schwindt es Doctora en Historia por la Universidad Nacional de Mar del Plata. Especialista en la Baja Edad Media y la primera modernidad en España. Sus investigaciones se centran en la historia de Castilla durante la Baja Edad Media y los inicios de la Edad Moderna a través de los postulados de la historia sensorial.\nEs Profesora Adjunta en la Universidad Nacional del Centro de la Provincia de Buenos Aires y en la Universidad Nacional de Mar del Plata.", contacto: "mailto:coronadogisela@gmail.com", publicaciones: "https://socunicen.academia.edu/GiselaCoronadoSchwindt" },
  { nombre: "Yolanda de Paz Trueba", descripcion: "Yolanda de Paz Trueba es Doctora en Historia por la Universidad Nacional del Centro de la Provincia de Buenos Aires. Ha investigado sobre el lugar de las mujeres en la esfera pública a fines del siglo XIX y primeras décadas del XX, y sobre las prácticas sociales, políticas e institucionales en torno a la infancia (especialmente las niñas) entre 1880 y 1920 en la provincia de Buenos Aires. Actualmente sus investigaciones están orientadas al estudio de los procesos de reconfiguración asistencial en la provincia de Buenos Aires en las primeras décadas del siglo XX.\nEs Investigadora Independiente del CONICET y Profesora Titular en el Departamento de Historia de la Facultad de Ciencias Humanas (UNICEN).", contacto: "mailto:yolidepaz@gmail.com", publicaciones: "https://bicyt.conicet.gov.ar/fichas/p/yolanda-edith-de-paz-trueba" },
  { nombre: "Pablo De Grande", descripcion: "Pablo De Grande es Doctor en Ciencias Sociales y Humanidades por la Universidad Nacional de Quilmes y Licenciado en Sociología por la Universidad de Buenos Aires. Investiga temáticas vinculadas con la primera infancia y los cuidados.\nEs Investigador Independiente del CONICET y docente en la Universidad Nacional del Centro de la Provincia de Buenos Aires.", contacto: "mailto:pablodg@gmail.com", publicaciones: "https://bicyt.conicet.gov.ar/fichas/p/pablo-ernesto-de-grande" },
  { nombre: "Soledad González", descripcion: "María Soledad González es Doctora en Historia por la Universidad Nacional del Centro de la Provincia de Buenos Aires. Sus intereses giran en torno a la historia cultural, los estudios de género y la historia de la educación.", contacto: "mailto:msgonzalez@live.com.ar", publicaciones: "https://www.conicet.gov.ar/new_scp/detalle.php?keywords=&id=52616&datos_academicos=yes" },
  { nombre: "Paola Gallo", descripcion: "Paola Gallo es Profesora y Licenciada en Historia, Diplomada en Estudios Avanzados de Cultura y Sociedad por el Instituto de Altos Estudios Sociales de la Universidad Nacional de San Martín, y Doctora en Historia por la Universidad Nacional del Centro de la Provincia de Buenos Aires.\nSus investigaciones giran en torno a la historia de la familia y la educación, con especial énfasis en las dinámicas modernizadoras del siglo XX y sus efectos sobre las sociabilidades, los patrones normativos y las prácticas de representación; historia a escala de la prensa como actor socio-cultural.\nEs Profesora Adjunta en la Universidad Nacional del Centro de la Provincia de Buenos Aires.", contacto: "mailto:agallo544@gmail.com", publicaciones: "https://scholar.google.com/citations?user=WPKgj2cAAAAJ&hl=es&oi=ao" },
  { nombre: "María de la Paz Bidauri", descripcion: "María de la Paz Bidauri es Licenciada y Profesora de Sociología y Doctora en Ciencias Sociales por la Universidad Nacional de La Plata. Sus intereses de investigación son la sociología del trabajo (trayectorias laborales, programas de empleo e inserción), la sociología y economía de la educación (trayectorias educativas, modalidad de educación técnico-profesional, programas de terminalidad abordando la dinámica educación-trabajo) y la desigualdad social abordando dimensiones como género, edad y clase social.", contacto: "mailto:paz.bidauri86@gmail.com", publicaciones: "https://www.conicet.gov.ar/new_scp/detalle.php?id=49138&datos_academicos=yes" },
  { nombre: "Magdalena López Pons", descripcion: "Magdalena López Pons es Diplomada Superior en Ciencias Sociales con mención en Género y Políticas Públicas (FLACSO), Magister en Ciencias Sociales con Mención en Desarrollo Regional (FCH-UNICEN) y en Género, Sociedad y Políticas (FLACSO), y doctoranda en Educación (FCH-UNICEN). Actualmente, desarrollo investigaciones vinculadas con los procesos de elaboración de tesis y trabajos finales de grado en estudiantes universitarios, con el propósito de analizar las dificultades que inciden en los retrasos y la deserción durante la etapa de graduación. Para ello, empleo enfoques metodológicos cualitativos que permiten profundizar en las experiencias de los estudiantes dentro de las instituciones de educación superior.", contacto: "mailto:lopezpons@fch.unicen.edu.ar", publicaciones: "https://socunicen.academia.edu/MariaMagdalenaLopezPons" },
  { nombre: "Ricardo Pasolini", descripcion: "Ricardo Pasolini es Doctor en Historia por la Universidad Nacional del Centro de la Provincia de Buenos Aires. Sus investigaciones giran en torno a la historia de los intelectuales en perspectiva comparativa y regional Europa-Argentina-Interior, formaciones culturales, sociabilidades e identidades políticas; la historia de las ideas estéticas y de los consumos culturales; y la epistemología y metodología de las ciencias del espíritu.\nEs Investigador Independiente CONICET y Profesor Titular en la Facultad de Ciencias Humanas (UNICEN)", contacto: "mailto:pasolini@fch.unicen.edu.ar", publicaciones: "https://www.conicet.gov.ar/new_scp/detalle.php?id=24338&datos_academicos=yes" },
  { nombre: "Juan Ignacio Quintián", descripcion: "Juan Ignacio Quintián es Doctor en Historia por la Universidad de San Andrés. Su trabajo de investigación se centra en el estudio de la formación de elites políticas y su relación con la consolidación de los estados nacionales. Actualmente se interesa en el estudio de los comandantes militares que actuaron en los espacios de frontera y contribuyeron la formación de un orden político nacional.\nEs Profesor Adjunto en el Departamento de Historia de la Facultad de Ciencias Humanas (UNICEN)", contacto: "mailto:juanignacioquintian@gmail.com", publicaciones: "https://scholar.google.com/citations?user=wvja2z4AAAAJ&hl=es&oi=ao" },
  { nombre: "Gisela Sedeillan", descripcion: "Gisela Sedeillan es Licenciada y Doctora en Historia por la Universidad Nacional del Centro de la Provincia de Buenos Aires. Su investigación se centra en analizar el diseño de políticas públicas en materia de justicia penal y en la praxis judicial en la provincia de Buenos Aires en las últimas décadas del siglo XIX y primeras del XX. Desde los últimos años indaga en particular en el periodo que va de 1906 a 1930, se detiene en distintos proyectos legislativos, en los cambios en la legislación y en las prácticas con el fin de identificar las transformaciones experimentadas en la organización y funcionamiento de los tribunales.\nEs Investigadora Adjunta CONICET y Profesora Adjunta en la Universidad Nacional de Mar del Plata.", contacto: "mailto:giselatandil@hotmail.com", publicaciones: "https://www.conicet.gov.ar/new_scp/detalle.php?id=34471&datos_academicos=yes" },
  { nombre: "Martín Vicente", descripcion: "Martín Vicente es Licenciado en Comunicación Social, Magíster en Ciencia Política y Doctor en Ciencias Sociales. Su trabajo se centra en la historia político-intelectual de las derechas, con especial énfasis en la tradición liberal-conservadora argentina en el siglo XX. En los últimos años ha trabajado en la biografía político-intelectual de Mariano Grondona y en la historia y actualidad de las derechas argentinas.\nEs Investigador Adjunto CONICET y docente en la carrera de Ciencia Política de la Facultad de Humanidades de la Universidad Nacional de Mar del Plata.", contacto: "mailto:vicentemartin28@gmail.com", publicaciones: "https://www.conicet.gov.ar/new_scp/detalle.php?id=29917&datos_academicos=yes" },
  { nombre: "Melina Yangilevich", descripcion: "Melina Yangilevich es Doctora en Historia por la Universidad Nacional del Centro de la Provincia de Buenos Aires. Su trabajo de investigación se centra en la administración de justicia de paz y criminal, así como en las prácticas relativas al castigo legal en la Provincia de Buenos Aires durante el siglo XIX en el contexto de creación/consolidación estatal.\nEs Investigadora Independiente del CONICET y Profesora Titular en el Departamento de Historia de la Facultad de Ciencias Humanas (UNICEN).", contacto: "mailto:myangilevich@gmail.com", publicaciones: "https://www.conicet.gov.ar/new_scp/detalle.php?id=30061&datos_academicos=yes" },
  { nombre: "Daniel Dicósimo", emerito: true }, { nombre: "Julio Melón Pirro", emerito: true }, { nombre: "Eduardo Míguez", emerito: true }, { nombre: "Marcelino Iriani", emerito: true }, { nombre: "Estela Spinelli", emerito: true }, { nombre: "Lucía Lionetti", emerito: true },
];

export default function Investigadores() {
  const [seleccionado, setSeleccionado] = useState<Investigador | null>(null);
  useEffect(() => { const cerrar = (event: KeyboardEvent) => { if (event.key === "Escape") setSeleccionado(null); }; window.addEventListener("keydown", cerrar); return () => window.removeEventListener("keydown", cerrar); }, []);
  const enlace = "text-[#134e5e] underline-offset-4 hover:text-[#f9623e] hover:underline focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#f9623e]";
  return <section className="max-w-5xl mx-auto px-4 py-12">
    <h1 className="text-4xl md:text-5xl font-extrabold mb-10 text-center bg-gradient-to-r from-[#134e5e] via-[#22677e] to-[#f9623e] bg-clip-text text-transparent drop-shadow-md tracking-tight leading-relaxed">Investigadores</h1>
    <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
      {investigadores.map((inv) => inv.emerito ? <article key={inv.nombre} className="flex h-full min-h-[225px] items-center justify-center rounded-3xl border border-[#134e5e]/15 bg-white px-6 py-8 text-center shadow-xl"><h2 className="text-[1.1rem] font-semibold text-[#134e5e]">{inv.nombre} (Emérito)</h2></article> : <article key={inv.nombre} className="flex flex-col rounded-3xl border border-[#134e5e]/15 bg-white p-6 shadow-xl transition-transform duration-200 hover:-translate-y-1"><p className="mb-1 text-xs uppercase tracking-wide text-[#134e5e]">Investigador/a</p><h2 className="mb-3 text-[1.1rem] font-semibold text-[#134e5e]">{inv.nombre}</h2><p className="mb-5 line-clamp-3 flex-1 text-sm text-gray-600">{inv.descripcion}</p><div className="flex flex-wrap gap-x-4 gap-y-2 border-t border-[#134e5e]/15 pt-4 text-sm font-medium"><button type="button" onClick={() => setSeleccionado(inv)} className={enlace}>Ver perfil</button><a href={inv.contacto} className={enlace}>Contacto</a><a href={inv.publicaciones} target="_blank" rel="noopener noreferrer" className={enlace}>Publicaciones</a></div></article>)}
    </div>
    {seleccionado && <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><button type="button" aria-label="Cerrar perfil" className="absolute inset-0 cursor-default bg-black/40" onClick={() => setSeleccionado(null)} /><div role="dialog" aria-modal="true" aria-labelledby="modal-investigador-titulo" className="relative z-10 w-full max-w-xl max-h-[calc(100vh-2rem)] overflow-y-auto rounded-[2rem] border border-[#22677e]/25 bg-gradient-to-br from-[#eaf3fa] via-[#f7fafc] to-[#fce4d6] px-8 py-10 shadow-2xl animate-fadein"><button type="button" onClick={() => setSeleccionado(null)} className="absolute right-4 top-3 text-2xl font-bold text-[#134e5e] hover:text-black focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#f9623e]" aria-label="Cerrar perfil">×</button><h2 id="modal-investigador-titulo" className="pr-8 text-center text-lg font-bold text-[#134e5e]">{seleccionado.nombre}</h2><div className="my-3 h-1 w-16 rounded-full bg-gradient-to-r from-[#134e5e] to-[#f9623e]" /><p className="whitespace-pre-line text-justify text-sm text-gray-800">{seleccionado.descripcion}</p><div className="mt-6 flex flex-wrap gap-4 text-sm font-medium"><a href={seleccionado.contacto} className={enlace}>Contacto</a><a href={seleccionado.publicaciones} target="_blank" rel="noopener noreferrer" className={enlace}>Publicaciones</a></div></div></div>}
    <style>{`@keyframes fadein { from { opacity: 0; transform: scale(0.96); } to { opacity: 1; transform: scale(1); } } .animate-fadein { animation: fadein 0.2s ease; }`}</style>
  </section>;
}
